backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: ../../static/images/

collections:
  - name: "portfolio"
    label: "portfolio"
    folder: "content/portfolio/"
    create: true
    slug: "{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {label: Image 1, name: Image01, widget: image}
      - {label: Image 1 - Alt Info, name: image1alt, widget: string }
      - { label: "Body", name: "body", widget: "markdown" }